### ISSUE TITLE
Please, release smtp.cr v0.2.0

### ISSUE THREAD

**Issue by faustinoaq** [raydf/smtp.cr#10]
Hi @raydf I'm having an issue building amber projects https://github.com/crystal-lang/shards/issues/183

I found this shard version don't follow common version pattern because is using `v0.1` instead of `v0.1.0` so you need to release `v0.2.0` to be able to fix my issue, please 😅 

Also don't release `v0.1.1` because doesn't work, seems that `shards install` logic is `v0.1.1 < v0.1` so `v0.2.0` is needed to be able to fix [this issue](https://github.com/crystal-lang/shards/issues/183)

Remember to update both, `shard.yml` and `src/version.cr` before create a tag 👍

**Comment by ray-delossantos** [comment]
Thanks @faustinoaq
