### ISSUE TITLE
Usage in another project

### ISSUE THREAD

**Issue by bararchy** [raydf/smtp.cr#5]
Hi :)
I want to use your code (or parts of it) in my Mail server project.
Is that ok with you ? 

project is here --> https://github.com/bararchy/servo

**Comment by ray-delossantos** [comment]
Hi @bararchy:

Of course, this is an MIT licensed project, you can reuse the code as you like, but take in considerations the details of that license.

**Comment by bararchy** [comment]
Thanks :) I will.
