### ISSUE TITLE
Release a version

### ISSUE THREAD

**Issue by faustinoaq** [raydf/smtp.cr#9]
Hi @raydf We are using this shard on [Amber Framework](https://github.com/amberframework/quartz-mailer/blob/master/shard.yml#L15),

Please, Can you create a first tag/version to avoid unexpected changes on master? 😄 

Thank you for this shard!

**Comment by ray-delossantos** [comment]
Hi @faustinoaq :

Thanks for the issue. This has been done with release v0.1.

BR,

Rayner
